amazon-ion/ion-hash-go

.github/PULL_REQUEST_TEMPLATE.md
*Description of changes:*
Add PR template text with the appropriate license, fixing the line that appears below 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> Add PR template text with the appropriate license

base_serializer.go, go.mod, go.sum, hash_reader.go, hash_value.go, hash_writer.go, serializer.go
Issue #, if available:
* Add go mod file.
=> Add go mod file

base_serializer.go, err.go, go.mod, go.sum, hash_reader.go, hash_value.go, hash_writer.go, hasher.go, serializer.go
Provide implementation for stubbed hashReader functions.
=> Implement hashReader functions

base_serializer.go, err.go, hasher.go, scalar_serializer.go, stack.go, struct_serializer.go
Provide implementation for stubbed hasher functions.
=> Implement hasher

.github/workflows/go.yml, README.md, crypto_hasher.go
* Enable GitHub Actions 
1. build the code 
1. Format the code using `goimports`
* Updates README with the instructions to use for building and formatting code
=> build(Actions): build and format using goimports

.github/workflows/go.yml, README.md, hash_reader.go
* After enabling actions, the repo had build failures. Commented them out and added `FIXME` comments. Added a `panic` instead for now till we address it. 
* updates README with a build badge linked to the Actions tab
=> fix(build): comment breaking code and adds build badge

base_serializer.go, contants.go, crypto_hasher.go, crypto_hasher_provider.go, err.go, hash_writer.go, hasher.go, ion_hasher.go, ion_hasher_provider.go, scalar_serializer.go, serializer.go, struct_serializer.go
Provide implementation for stubbed base serializer functions.
=> Implement Base Serializer

README.md
Adds warning to README that this package is in early development and should be considered experimental. 
=> chore(README): adds warning that this package in early development

.github/workflows/go.yml, base_serializer.go, constants.go, crypto_hasher.go, crypto_hasher_provider.go, err.go, go.mod, hash_reader.go, hash_writer.go, ion_hasher.go, ion_hasher_provider.go, stack.go
1. Enable linter in GitHub Actions 
1. Applied fixes for linting issues. Made a couple of things private. 
See https://github.com/therapon/ion-hash-go/pull/2 for how linter errors appear as warning messages on a PR. 
**NOTE**: There is not mechanism to turn linting on/off inside a file. It is all or nothing, which is unfortunate. 
=> refactor: Adds linter and fixes linting issues

.github/workflows/go.yml
Adds steps to the current pipeline to run tests, generate code coverage results and upload code coverage results for PRs and pushes. 
=> build(Tests): Adds tests and codecoverage to CI/CD

base_serializer.go, reader_writer_test.go
Unit Tests for Reader and Writer
=> Unit Tests for Reader and Writer

naughty_strings_test.go
Implement Naughty Strings test
=> Naughty Strings Test

crypto_hasher.go, crypto_hasher_provider.go, crypto_hasher_test.go, naughty_strings_test.go
=> Unit Tests for Crypto Hasher

base_serializer.go, go.mod, hash_reader.go, hash_reader_test.go, hash_value.go, hash_writer.go, hash_writer_test.go, reader_writer_test.go, testing_utilities.go
Now that https://github.com/amzn/ion-go/issues/71 is resolved, we can enable several tests.
This PR increases our code coverage from 39.4% to 62.8%.
=> Enable tests now that IsInStruct() is implemented in ion-go

base_serializer.go, compare_bytes_test.go, struct_serializer.go
Add unit tests for compareBytes()
=> Add unit tests for compareBytes()

hash_writer_test.go
Expand hash writer tests to test more data types
=> Expand hash writer tests to test more data types

base_serializer.go, go.mod, go.sum, hash_reader.go, hash_value.go, hash_writer.go, hasher.go, ion_hash_test.go, scalar_serializer.go, testing_utilities.go
Resolves https://github.com/amzn/ion-hash-go/issues/46
=> Change return type of FieldName()

go.mod, go.sum, hash_reader_test.go, naughty_strings_test.go, reader_writer_test.go
=> Rename ion.NewReaderStr() to ion.NewReaderString()

README.md
Issue #, if available: Closes #19 
Adds basic info in the README file including sample usage of the library. 
=> docs: Updates README for beta release

.github/workflows/go.yml, hash_reader_test.go, hash_writer_test.go, naughty_strings_test.go, reader_writer_test.go, testing_utilities.go
=> Fix Naughty Strings test

go.mod, go.sum
* Updated `ion-go` dependency to v1.0.1
* `go mod tidy`
=> Updated ion-go to v1.0.1
